workflows:
  ios-maui-release:
    name: iOS MAUI Release - Manual Signing
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: "Codemagic API Key"

    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    scripts:
      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list

      - name: Restore NuGet packages
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH" \
            /p:TargetFramework=net9.0-ios18.0

      - name: Setup iOS code signing
        script: |
          set -e
          python3 -m pip install --upgrade codemagic-cli-tools
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
          echo "=== Certificates ==="
          security find-identity -v -p codesigning
          echo "=== Profiles ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

      - name: Build IPA (Release)
        script: |
          set -e

          # Signing identity bul
          SIGNING_IDENTITY=$(security find-identity -v -p codesigning | grep "Apple Distribution" | head -1 | awk -F'"' '{print $2}')
          echo "Signing identity: $SIGNING_IDENTITY"

          # Profile UUID bul
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_UUID=""
          for f in "$PROFILES_DIR"/*.mobileprovision; do
            UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin <<< $(security cms -D -i "$f") 2>/dev/null || true)
            APPID=$(/usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" /dev/stdin <<< $(security cms -D -i "$f") 2>/dev/null || true)
            if echo "$APPID" | grep -q "$BUNDLE_ID"; then
              PROFILE_UUID="$UUID"
              echo "Found profile UUID: $PROFILE_UUID"
              break
            fi
          done

          # Build + Sign (--no-restore YOK!)
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER \
            /p:CodesignKey="$SIGNING_IDENTITY" \
            /p:CodesignProvision="$PROFILE_UUID"

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false