workflows:
  ios-release:
    name: iOS Release - App Store
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    # API Key entegrasyonu
    integrations:
      app_store_connect: "Codemagic API Key"  # Yukarıda verdiğiniz isim
    
    environment:
      xcode: latest
      
      vars:
        # Bundle ID - .csproj ve Apple Developer'da kaydettiğiniz ile AYNI
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        
        # Proje yolu
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        
        # iOS Target Framework (.csproj'deki ile eşleşmeli)
        IOS_TFM: net9.0-ios
        
        # .NET yolu
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
      
      # Otomatik kod imzalama
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi
    
    scripts:
      # 1. .NET SDK Kurulumu
      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info
      
      # 2. MAUI Workload Kurulumu
      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list
      
      # 3. NuGet Paketlerini Geri Yükle
      - name: Restore NuGet packages
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"
      
      # 4. iOS Kod İmzalama (Otomatik)
      - name: Setup iOS code signing
        script: |
          set -e
          set -x  # Debug mode
          
          # Codemagic CLI tools
          python3 -m pip install --upgrade codemagic-cli-tools
          
          # Keychain hazırla
          keychain initialize
          
          echo "=== Bundle ID: $BUNDLE_ID ==="
          
          # Otomatik sertifika + provisioning profile oluştur/indir
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --verbose
          
          # Keychain'e ekle
          keychain add-certificates
          
          # Profilleri uygula
          xcode-project use-profiles
          
          # Doğrulama
          echo "=== Code Signing Identities ==="
          security find-identity -v -p codesigning | head -20
      
      # 5. IPA Build
      - name: Build IPA
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER
    
    # Build çıktıları
    artifacts:
      - "**/*.ipa"
    
    # TestFlight'a otomatik yükleme
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false  # Manuel App Store onayı için false