workflows:
  ios-create-p12:
    name: Create P12 Certificate
    instance_type: mac_mini_m2
    max_build_duration: 30
    
    environment:
      xcode: latest
    
    scripts:
      - name: Create P12 from CER and Private Key
        script: |
          set -e
          
          echo "🔐 Creating P12 certificate..."
          
          # Private Key dosyasını oluştur
          cat > distribution.key << 'EOF'
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDU/396FKur9pVk
CbB0HOzbL+MlX9D1gMEyNeGQfTW2o8kNVqQdrbcrgIkDRsy/ehyKMJX0DACWelhv
fGuln+bbkIxyrxk5Iafbxd41VGcCqFVXjeDr4O0q8xTjs2RGisHmUqUE0ntWu+S9
hHhGCLBmwvuOR0N7+I5dyRa39TzPQKABgvjsoQg7Xvre7bm5cvIVqshBFNrc+6T+
SJUi5WDB1lNR+BAnTBCf7EWsg1fTcZWTj+7YtYRSpxOeYY+T30P+JEgCE65pKUGg
HkibMYZ3VrBUzqu6e4PuZNqGaj8778eMniTL5DAlTXb8IhpkgiAk349BjqPE3x9w
CdfasHMFAgMBAAECggEACbjkKUmhFg9CPZJ5UNd9fToX7hML+e9yV20hBQ7Itp6O
al2Hzgipns1LaRBLKhCewF+xhzX2tJJUOo8tPQkJ3oBK1N+cBmD8T+UIfJqEEtmQ
VFfYH37WZy/jcSBKsF3xi1E+5zPcqDZuiAha/Wa0oerTqih5Eq3OARxmZ9JZv/j1
FjnCZLJJp1XtKZdMCCEjATtntrHIR+9jhQT5mVl8t8fN2Ev1MmATgCpgogtfeQ01
cFfoNhf/6gvlPrXkic1cJhrt0GYEfckatUG2cCbBiN8AaqCjIF58KNEZDyOaqAnP
tX0FqEirC+cad06Nl8QEDz9HYG4ADzHwogVLkKjx4QKBgQD2cO5dCDwGf4MABIJn
rRDVKLK2GBtY4gGeu/RVSyntJ2FMzq2OgJQF5YR9lZiq9MMvc5qp705mk1NUpzxP
JY1Is7PLQ4orMApXmwTw8pT1aLKGK7iALycdu28GsZKAl12hNl/OTL+vOMSclKFH
BeDQiLu6CMjfYmTHVpnDjctQ5QKBgQDdQn1Ds1QYtUjJHAEM6FGrpUiaypbhh/zj
WAuGvOOTKKaJNBkisfTKqMlmmBixhquBHPgJ5fumlTtYcqxHpxpaVA2bzXMFp2w/
s+Rfzq1hjrwEMg2u6dHiBrkMjn2bB7dKeaOLAiKK7jgUHPLf0pCjYCY0SAJDw+4c
SJj4oHYXoQKBgBdKoRyl1JaAoq7zvidyUe7zg8B2Es+ZvLF17ifJjNLfL/EEb57S
RCsygA0mgGFX9MKdWHbLKUvEjNGpZKfOUsYWRd3mKj7esXuKKTNkmfN/y6+mni9v
RXEn79xgGAqTQ8Qi0Xc8BbnX0a1C1uNRiOfspGF2xxVlxUSZyLqUwiyJAoGAcKrW
1o6OmDZX5fCYqFX0oI79tbTLt/RjVfETjXzJ9bmRc/RPiFdN65SfWdrBWETXOFvk
AkZWKrF7EsLx71qsFKsQcvHfTFXAzX9xH0hDCZaBLzG9vf/anFoICNjWJQd80jO2
j6Z6qHw9miBTnJ3AgTEIwz6XyKIQsd5V5uTuvYECgYB6ahw8u6lo8wOnScUuWFu3
budal5RWZUiesfvZU5esIBHyaiAD4uX/MjgNOFp51kLL2SyAzc48PISICg6O7Ac/
kE7G5P31+mavw9PdcCo0Y49wfQKcN8QV3SI5NSG7qFfTYPJOpNOwz9YwpcW1PGl3
55SqLytLQkweKaYtMRx5Aw==
-----END PRIVATE KEY-----
EOF
          
          # CER Base64 dosyasını oluştur
          cat > distribution.cer.b64 << 'EOF'
-----BEGIN CERTIFICATE-----
MIIFyzCCBLOgAwIBAgIQCGm9ylo2sXIoYHGtM7OVLjANBgkqhkiG9w0BAQsFADB1
MUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBD
ZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzMxEzARBgNVBAoMCkFw
cGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTI2MDIxNTE2NDY0N1oXDTI3MDIxNTE2
NDY0NlowgZExGjAYBgoJkiaJk/IsZAEBDApZMjc1UzVLMzdRMTgwNgYDVQQDDC9B
cHBsZSBEaXN0cmlidXRpb246IE5ldHJvbiBZYXppbGltIChZMjc1UzVLMzdRKTET
MBEGA1UECwwKWTI3NVM1SzM3UTEXMBUGA1UECgwOTmV0cm9uIFlhemlsaW0xCzAJ
BgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0MjJPJvm
q9OcPrfKNm8ZtZm13ZONIFhikFONJaCnf4FHWrDmLTuGOmMiCl8CfY389IERiEna
ShTro+BEkL26jpYc5R0JNXJKGJWav3IjjnhqaLAX5dVsAwCbDyyxPChsKlFrXbBi
gdRS4d91b1jDkfnD1i5RHN4ARKApK1drgLeMpF5wVAIEei2Vl2fknzMg7u49u4WY
W0dOnwpx/hFwIzjCEJwSuDV8FfpR0VkaGUdic5nJGL/LRXzWZ6rCtPmweEkQbS0k
1FGvER95kCOqbZtfKWvWBcDOic0Dwm2dVWiwZHOXSd2fFOLP83hgdBeqGz1fBZ0+
p3r4d1BfRIjnIwIDAQABo4ICODCCAjQwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAW
gBQJ/sAVkPmvZAqSErkmKGMMl+ynsjBwBggrBgEFBQcBAQRkMGIwLQYIKwYBBQUH
MAKGIWh0dHA6Ly9jZXJ0cy5hcHBsZS5jb20vd3dkcmczLmRlcjAxBggrBgEFBQcw
AYYlaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy13d2RyZzMwNTCCAR4GA1Ud
IASCARUwggERMIIBDQYJKoZIhvdjZAUBMIH/MIHDBggrBgEFBQcCAjCBtgyBs1Jl
bGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMg
YWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1z
IGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBj
ZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDcGCCsGAQUFBwIBFito
dHRwczovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMBYGA1Ud
JQEB/wQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBSxd69+mB1RFQ+qErlajSMuS3Cr
tDAOBgNVHQ8BAf8EBAMCB4AwEwYKKoZIhvdjZAYBBwEB/wQCBQAwEwYKKoZIhvdj
ZAYBBAEB/wQCBQAwDQYJKoZIhvcNAQELBQADggEBAJEvqvd0So7ggeoB0LGHW4Zg
7J81mMyUXDbZWU0nWsPWq8+mIsk6vPfH41VVgYv82uzex9CcGDR+7u1ff1NfRyJV
s5ZvREx+ebpXtO7ioniQOLKfX5kQelJ5v4597YP3C9vBUTRJM9vMUSYVIL2+kzcH
AKOajsUO085Wcka9g4QkPE0kBp0yeRLfZiNO4igsgjPUuLUbwPTooRVXKP0ZS0io
++WVvq1dua9DpcHmrC8yE949FFf5sy3hvtN4iYCV7ZltR4qdkmpCV/4MKmZvr18l
Kuu10KcDsjTl2yP5ohGV14c4rWwMtbdFvN2+VQJHE3xVuoeoHHcSR5/k7pS0SXk=
-----END CERTIFICATE-----
EOF
          
          echo "📦 Decoding CER file..."
          base64 -d distribution.cer.b64 > distribution.cer
          
          echo "🔄 Converting CER to PEM..."
          openssl x509 -in distribution.cer -inform DER -out distribution.pem -outform PEM
          
          echo "🔐 Creating P12 file..."
          openssl pkcs12 -export \
            -inkey distribution.key \
            -in distribution.pem \
            -out distribution.p12 \
            -password pass:Codemagic2026
          
          echo ""
          echo "==============================================="
          echo "    P12 CERTIFICATE (BASE64) - COPY THIS"
          echo "==============================================="
          base64 distribution.p12
          echo "==============================================="
          echo ""
          echo "✅ P12 created successfully!"
          echo "Password: Codemagic2026"
          echo ""
          echo "NEXT STEPS:"
          echo "1. Copy the BASE64 block above"
          echo "2. Save it to a text file"
          echo "3. Decode it to get distribution.p12"