workflows:
  ios-maui-release:
    name: iOS MAUI Release (IPA + TestFlight) - Auto Signing (Fixed)
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: "Codemagic API Key"

    environment:
      xcode: latest

      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0

        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    scripts:
      - name: Install Codemagic CLI tools (pip)
        script: |
          set -e
          python3 --version
          python3 -m pip --version

          USER_BASE="$(python3 -m site --user-base)"
          export PATH="$USER_BASE/bin:$PATH"

          python3 -m pip install --upgrade --user pip
          python3 -m pip install --upgrade --user codemagic-cli-tools

          echo "== CLI tools =="
          which keychain || true
          which xcode-project || true
          which app-store-connect || true

          keychain --version || true
          xcode-project --version || true
          app-store-connect --version || true

      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list

      - name: Restore
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Setup signing in keychain (MUST)
        script: |
          set -e

          USER_BASE="$(python3 -m site --user-base)"
          export PATH="$USER_BASE/bin:$PATH"

          keychain initialize

          echo "== BEFORE: identities =="
          security find-identity -v -p codesigning || true

          # 1) Codemagic environment'daki signing assets'i çekmeyi dene (komut sürüme göre değişebilir)
          if xcode-project --help | grep -q "fetch-signing-files"; then
            echo "Using: xcode-project fetch-signing-files"
            xcode-project fetch-signing-files --platform ios --type app_store --bundle-id "$BUNDLE_ID"
          else
            echo "xcode-project fetch-signing-files not found in this version. Skipping fetch."
          fi

          # 2) Sertifikaları keychain'e import et (kritik!)
          if keychain --help | grep -q "add-certificates"; then
            keychain add-certificates
          else
            echo "keychain add-certificates not available."
          fi

          # 3) Provisioning profilleri uygula
          xcode-project use-profiles

          echo "== AFTER: identities =="
          security find-identity -v -p codesigning | head -n 50 || true

          # Apple Distribution identity zorunlu
          if ! security find-identity -v -p codesigning | grep -q "Apple Distribution"; then
            echo "ERROR: Apple Distribution identity not found in keychain after signing setup."
            exit 1
          fi

      - name: Build IPA (Release) + auto build number
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
