workflows:
  ios-maui-release:
    name: iOS MAUI Release - Auto Signing
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    integrations:
      app_store_connect: "Codemagic API Key"
    
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi
    
    scripts:
      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info
      
      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list
      
      - name: Restore
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"
      
      - name: Setup iOS code signing (Automatic)
        script: |
          set -e
          set -x
          
          python3 -m pip install --upgrade codemagic-cli-tools
          
          keychain initialize
          
          echo "=== Bundle ID: $BUNDLE_ID ==="
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --verbose
          
          keychain add-certificates
          xcode-project use-profiles
          
          echo "=== Code Signing Identities ==="
          security find-identity -v -p codesigning | head -20
      
      - name: Build IPA (Release)
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER
    
    artifacts:
      - "**/*.ipa"
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false