workflows:
  ios-maui-release:
    name: iOS MAUI Build & Upload to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - IOS
      xcode: latest
      vars:
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    integrations:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

    scripts:
      - name: Install .NET SDK (9.0)
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads (iOS)
        script: |
          "$DOTNET" workload install ios maui
          "$DOTNET" workload list

      - name: Restore
        script: |
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Build IPA (Release)
        script: |
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            -p:ArchiveOnBuild=true \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignProvision=Automatic \
            -p:CodesignKey="Apple Distribution"

      - name: Find IPA
        script: |
          find "$CM_BUILD_DIR" -name "*.ipa" -print

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
