workflows:
  ios-maui-release:
    name: iOS MAUI Build & Upload to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - IOS
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0

        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

        # p12 şifresi (fetch-signing-files p12 üretirken kullanıyor)
        P12_PASSWORD: codemagic

    scripts:
      - name: Install .NET SDK (9.0)
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install ios maui
          "$DOTNET" workload list

      - name: Restore
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Debug env vars (length only)
        script: |
          echo "ISSUER len: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "KEY_ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER}"
          echo "P8 len: ${#APP_STORE_CONNECT_PRIVATE_KEY}"
          echo "CERT key len: ${#CERTIFICATE_PRIVATE_KEY}"

- name: Setup iOS signing (stable)
  script: |
    set -e

    KEYCHAIN_PATH="$CM_BUILD_DIR/build.keychain-db"
    KEYCHAIN_PASSWORD="codemagic"

    # 1) Keychain oluştur + default yap + listeye ekle
    security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
    security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain-db
    security default-keychain -s "$KEYCHAIN_PATH"

    # 2) Cert & profile çek
    CERT_DIR="$CM_BUILD_DIR/signing/certs"
    PROF_DIR="$CM_BUILD_DIR/signing/profiles"
    mkdir -p "$CERT_DIR" "$PROF_DIR"

    app-store-connect fetch-signing-files "$BUNDLE_ID" \
      --type IOS_APP_STORE \
      --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
      --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
      --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
      --certificate-key "$CERTIFICATE_PRIVATE_KEY" \
      --p12-password "$P12_PASSWORD" \
      --certificates-dir "$CERT_DIR" \
      --profiles-dir "$PROF_DIR" \
      --create

    # 3) p12 import (dosya olarak bul)
    P12_PATH="$(find "$CERT_DIR" -maxdepth 1 -type f -name "*.p12" | head -n 1)"
    if [ -z "$P12_PATH" ]; then
      echo "ERROR: No .p12 found in $CERT_DIR"
      exit 1
    fi
    echo "Using P12: $P12_PATH"

    security import "$P12_PATH" -k "$KEYCHAIN_PATH" -P "$P12_PASSWORD" \
      -T /usr/bin/codesign -T /usr/bin/security

    # 4) KRİTİK: partition list için keychain şifresi kullanılır
    security set-key-partition-list -S apple-tool:,apple: -s \
      -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

    # 5) Provisioning profile kopyala
    mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
    cp -R "$PROF_DIR"/*.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

    # 6) Kontrol: identity görünüyor mu? (default keychain üzerinden)
    echo "== Keychains =="
    security list-keychains -d user
    echo "== Codesigning identities =="
    security find-identity -v -p codesigning
    security find-identity -v -p codesigning | grep -q "Apple"

        script: |
          set -e

          # 1) Keychain oluştur (Codemagic CLI)
          keychain initialize

          # 2) En yeni keychain dosyasını bul (stabil)
          KEYCHAIN_DIR="$HOME/Library/codemagic-cli-tools/keychains"
          KEYCHAIN_PATH="$(ls -t "$KEYCHAIN_DIR"/*.keychain-db | head -n 1)"
          echo "Using KEYCHAIN_PATH=$KEYCHAIN_PATH"

          # Default keychain yap
          security default-keychain -s "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH" login.keychain-db

          # 3) Cert & profile çek (create if needed)
          CERT_DIR="$CM_BUILD_DIR/signing/certs"
          PROF_DIR="$CM_BUILD_DIR/signing/profiles"
          mkdir -p "$CERT_DIR" "$PROF_DIR"

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "$CERTIFICATE_PRIVATE_KEY" \
            --p12-password "$P12_PASSWORD" \
            --certificates-dir "$CERT_DIR" \
            --profiles-dir "$PROF_DIR" \
            --create

          echo "== Downloaded signing files =="
          ls -la "$CERT_DIR" || true
          ls -la "$PROF_DIR" || true

          # 4) p12 dosyasını kesin DOSYA olarak bul
          P12_PATH="$(find "$CERT_DIR" -maxdepth 1 -type f -name "*.p12" | head -n 1)"
          if [ -z "$P12_PATH" ]; then
            echo "ERROR: No .p12 found in $CERT_DIR"
            exit 1
          fi
          echo "Using P12: $P12_PATH"

          # 5) p12 import
          security import "$P12_PATH" -k "$KEYCHAIN_PATH" -P "$P12_PASSWORD" \
            -T /usr/bin/codesign -T /usr/bin/security

          # 6) Private key izinleri (bazı ortamlarda şart)
          security set-key-partition-list -S apple-tool:,apple: -s \
            -k "$P12_PASSWORD" "$KEYCHAIN_PATH" || true

          # 7) Provisioning profile yükle
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp -R "$PROF_DIR"/*.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/" || true

          # 8) Kontrol: identity var mı?
          echo "== Codesigning identities =="
          security find-identity -v -p codesigning "$KEYCHAIN_PATH" || true
          security find-identity -v -p codesigning "$KEYCHAIN_PATH" | grep -q "Apple"

      - name: Build IPA (Release)
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" -c Release -f "$IOS_TFM" /p:BuildIpa=true

      - name: Find IPA
        script: |
          find "$CM_BUILD_DIR" -name "*.ipa" -print

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
