workflows:
  ios-maui-release:
    name: iOS MAUI Release (IPA + TestFlight) - Auto Signing
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: "Codemagic API Key"

    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0

        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    scripts:
      - name: Install Codemagic CLI tools (needed for keychain/use-profiles)
        script: |
          set -e
          if ! command -v xcode-project >/dev/null 2>&1; then
            brew update
            brew install codemagic-cli-tools
          fi
          xcode-project --version || true
          keychain --version || true
          fetch-signing-files --version || true

      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list

      - name: Restore
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Fetch signing files + apply iOS signing (auto)
        script: |
          set -e

          # 1) Yeni keychain
          keychain initialize

          # 2) Apple Developer Portal'dan App Store sertifika + profile çek (yoksa oluştur)
          fetch-signing-files \
            --platform ios \
            --type app_store \
            --bundle-id "$BUNDLE_ID" \
            --create

          # 3) Çekilenleri projeye uygula
          xcode-project use-profiles

          echo "== Codesigning identities =="
          security find-identity -v -p codesigning | head -n 50

          if ! security find-identity -v -p codesigning | grep -q "Apple Distribution"; then
            echo "ERROR: Apple Distribution identity not found in keychain."
            exit 1
          fi

      - name: Build IPA (Release) + Auto build number
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
