workflows:
  ios-maui-release:
    name: iOS MAUI Build & Upload to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - IOS
      xcode: latest
      vars:
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    scripts:
      - name: Install .NET SDK (9.0)
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads (iOS)
        script: |
          "$DOTNET" workload install ios maui
          "$DOTNET" workload list

      - name: Restore
        script: |
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Import iOS signing (from base64)
        script: |
          set -e

          CERT_PATH="$CM_BUILD_DIR/ios_distribution.p12"
          PROFILE_PATH="$CM_BUILD_DIR/appstore.mobileprovision"

          python3 - <<'PY'
          import os, base64, pathlib
          cert_b64 = os.environ["CM_P12_B64"]
          prof_b64 = os.environ["CM_PROFILE_B64"]
          build_dir = pathlib.Path(os.environ["CM_BUILD_DIR"])
          cert_path = build_dir / "ios_distribution.p12"
          prof_path = build_dir / "appstore.mobileprovision"
          cert_path.write_bytes(base64.b64decode(cert_b64))
          prof_path.write_bytes(base64.b64decode(prof_b64))
          print("Wrote:", cert_path, "bytes:", cert_path.stat().st_size)
          print("Wrote:", prof_path, "bytes:", prof_path.stat().st_size)
          PY

          KEYCHAIN_PASSWORD=codemagic
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security list-keychains -d user -s build.keychain login.keychain
          security default-keychain -s build.keychain

          security import "$CERT_PATH" -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/"

      - name: Build IPA (Release)
        script: |
          "$DOTNET" publish "$PROJECT_PATH" -c Release -f "$IOS_TFM" /p:BuildIpa=true

      - name: Find IPA
        script: |
          find . -name "*.ipa" -print

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        api_key: $T_APPSTORE_API_KEY
        key_id: $T_KEY_ID
        issuer_id: $T_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
