workflows:
  ios-create-p12:
    name: Create P12 Certificate
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      xcode: latest

    scripts:
      - name: Create P12 from CER and Private Key
        script: |
          set -e

          echo "Creating P12 certificate..."

          cat > distribution.key <<'KEYEOF'
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDU/396FKur9pVk
          CbB0HOzbL+MlX9D1gMEyNeGQfTW2o8kNVqQdrbcrgIkDRsy/ehyKMJX0DACWelhv
          fGuln+bbkIxyrxk5Iafbxd41VGcCqFVXjeDr4O0q8xTjs2RGisHmUqUE0ntWu+S9
          hHhGCLBmwvuOR0N7+I5dyRa39TzPQKABgvjsoQg7Xvre7bm5cvIVqshBFNrc+6T+
          SJUi5WDB1lNR+BAnTBCf7EWsg1fTcZWTj+7YtYRSpxOeYY+T30P+JEgCE65pKUGg
          HkibMYZ3VrBUzqu6e4PuZNqGaj8778eMniTL5DAlTXb8IhpkgiAk349BjqPE3x9w
          CdfasHMFAgMBAAECggEACbjkKUmhFg9CPZJ5UNd9fToX7hML+e9yV20hBQ7Itp6O
          al2Hzgipns1LaRBLKhCewF+xhzX2tJJUOo8tPQkJ3oBK1N+cBmD8T+UIfJqEEtmQ
          VFfYH37WZy/jcSBKsF3xi1E+5zPcqDZuiAha/Wa0oerTqih5Eq3OARxmZ9JZv/j1
          FjnCZLJJp1XtKZdMCCEjATtntrHIR+9jhQT5mVl8t8fN2Ev1MmATgCpgogtfeQ01
          cFfoNhf/6gvlPrXkic1cJhrt0GYEfckatUG2cCbBiN8AaqCjIF58KNEZDyOaqAnP
          tX0FqEirC+cad06Nl8QEDz9HYG4ADzHwogVLkKjx4QKBgQD2cO5dCDwGf4MABIJn
          rRDVKLK2GBtY4gGeu/RVSyntJ2FMzq2OgJQF5YR9lZiq9MMvc5qp705mk1NUpzxP
          JY1Is7PLQ4orMApXmwTw8pT1aLKGK7iALycdu28GsZKAl12hNl/OTL+vOMSclKFH
          BeDQiLu6CMjfYmTHVpnDjctQ5QKBgQDdQn1Ds1QYtUjJHAEM6FGrpUiaypbhh/zj
          WAuGvOOTKKaJNBkisfTKqMlmmBixhquBHPgJ5fumlTtYcqxHpxpaVA2bzXMFp2w/
          s+Rfzq1hjrwEMg2u6dHiBrkMjn2bB7dKeaOLAiKK7jgUHPLf0pCjYCY0SAJDw+4c
          SJj4oHYXoQKBgBdKoRyl1JaAoq7zvidyUe7zg8B2Es+ZvLF17ifJjNLfL/EEb57S
          RCsygA0mgGFX9MKdWHbLKUvEjNGpZKfOUsYWRd3mKj7esXuKKTNkmfN/y6+mni9v
          RXEn79xgGAqTQ8Qi0Xc8BbnX0a1C1uNRiOfspGF2xxVlxUSZyLqUwiyJAoGAcKrW
          1o6OmDZX5fCYqFX0oI79tbTLt/RjVfETjXzJ9bmRc/RPiFdN65SfWdrBWETXOFvk
          AkZWKrF7EsLx71qsFKsQcvHfTFXAzX9xH0hDCZaBLzG9vf/anFoICNjWJQd80jO2
          j6Z6qHw9miBTnJ3AgTEIwz6XyKIQsd5V5uTuvYECgYB6ahw8u6lo8wOnScUuWFu3
          budal5RWZUiesfvZU5esIBHyaiAD4uX/MjgNOFp51kLL2SyAzc48PISICg6O7Ac/
          kE7G5P31+mavw9PdcCo0Y49wfQKcN8QV3SI5NSG7qFfTYPJOpNOwz9YwpcW1PGl3
          55SqLytLQkweKaYtMRx5Aw==
          -----END PRIVATE KEY-----
          KEYEOF

          cat > distribution.cer.b64 <<'CEREOF'
          -----BEGIN CERTIFICATE-----
          MIIFyzCCBLOgAwIBAgIQCGm9ylo2sXIoYHGtM7OVLjANBgkqhkiG9w0BAQsFADB1
          ... (kalan sertifika içeriği aynı şekilde) ...
          -----END CERTIFICATE-----
          CEREOF

          echo "Decoding CER..."
          base64 -d distribution.cer.b64 > distribution.cer

          echo "Converting to PEM..."
          openssl x509 -in distribution.cer -inform DER -out distribution.pem -outform PEM

          echo "Creating P12..."
          openssl pkcs12 -export -inkey distribution.key -in distribution.pem -out distribution.p12 -password pass:Codemagic2026

          echo ""
          echo "========================================"
          echo "P12 BASE64 - COPY EVERYTHING BELOW"
          echo "========================================"
          base64 distribution.p12
          echo "========================================"
          echo ""
          echo "Password: Codemagic2026"