workflows:
  ios-maui-release:
    name: iOS MAUI Release (IPA + TestFlight) - Auto Signing
    integrations:
      app_store_connect: NetronASCKey   # UI'da verdiğin API key name

    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi.ios
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi.ios

    scripts:
      - name: Restore
        script: |
          set -e
          dotnet --info
          dotnet restore "$PROJECT_PATH"

      - name: Build IPA (Release) + Auto build number
        script: |
          set -e
          dotnet publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
