workflows:
  ios-maui-release:
    name: iOS MAUI Release (IPA + TestFlight) - Auto Signing
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: "Codemagic API Key"

    environment:
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.netronyazilim.ogrencibilgisistemi

    scripts:
      - name: Install Codemagic CLI tools (pip) + verify
        script: |
          set -e
          python3 --version
          python3 -m pip --version
          USER_BASE="$(python3 -m site --user-base)"
          export PATH="$USER_BASE/bin:$PATH"
          python3 -m pip install --upgrade --user pip
          python3 -m pip install --upgrade --user codemagic-cli-tools
          echo "== CLI tools =="
          which app-store-connect
          which keychain
          which xcode-project
          keychain --version || true
          xcode-project --version || true

      - name: Install .NET SDK 9.0
        script: |
          set -e
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads
        script: |
          set -e
          "$DOTNET" workload install maui-ios maui --skip-manifest-update
          "$DOTNET" workload list

      - name: Restore
        script: |
          set -e
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Fetch signing files + apply iOS signing (App Store)
        script: |
          set -e
          USER_BASE="$(python3 -m site --user-base)"
          export PATH="$USER_BASE/bin:$PATH"

          keychain initialize

          echo "== Certificates before =="
          app-store-connect certificates list || true

          echo "== Profiles before =="
          app-store-connect profiles list || true

          # App Store signing files (profile + related cert metadata)
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          echo "== Certificates after =="
          app-store-connect certificates list || true

          echo "== Profiles after =="
          app-store-connect profiles list || true

          # import certs (must include private key to produce Apple Distribution identity)
          keychain add-certificates

          echo "== Codesigning identities (after add-certificates) =="
          security find-identity -v -p codesigning | head -n 80

          if ! security find-identity -v -p codesigning | grep -q "Apple Distribution"; then
            echo "ERROR: Apple Distribution identity not found in keychain. (No matching certificate+private key)"
            exit 1
          fi

          xcode-project use-profiles

      - name: Build IPA (Release) + auto build number
        script: |
          set -e
          "$DOTNET" publish "$PROJECT_PATH" \
            -c Release \
            -f "$IOS_TFM" \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:ArchiveOnBuild=true \
            /p:BuildIpa=true \
            /p:ApplicationVersion=$CM_BUILD_NUMBER

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
