workflows:
  ios-generate-csr:
    name: Generate CSR and Private Key
    instance_type: mac_mini_m2
    max_build_duration: 30
    
    environment:
      xcode: latest
    
    scripts:
      - name: Generate CSR and Private Key
        script: |
          set -e
          
          echo "🔐 Generating CSR and Private Key..."
          
          # CSR ve Private Key oluştur
          openssl req -new -newkey rsa:2048 -nodes \
            -keyout distribution.key \
            -out distribution.csr \
            -subj "/emailAddress=yazilinmetron@gmail.com/CN=Netron Yazilim/C=TR"
          
          echo ""
          echo "==============================================="
          echo "    COPY THIS CSR - SAVE TO distribution.csr"
          echo "==============================================="
          cat distribution.csr
          echo "==============================================="
          echo ""
          
          echo ""
          echo "==============================================="
          echo "    COPY THIS PRIVATE KEY - SAVE SECURELY!"
          echo "==============================================="
          cat distribution.key
          echo "==============================================="
          echo ""
          
          echo "✅ DONE! Copy both blocks above."
          echo ""
          echo "NEXT STEPS:"
          echo "1. Copy the CSR block (including BEGIN/END lines)"
          echo "2. Save it to a file named: distribution.csr"
          echo "3. Copy the PRIVATE KEY block (including BEGIN/END lines)"
          echo "4. Save it to a file named: distribution.key"
          echo "5. Upload distribution.csr to Apple Developer Portal"