workflows:
  ios-maui-release:
    name: iOS MAUI Build & Upload to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - IOS
      xcode: latest
      vars:
        BUNDLE_ID: com.netronyazilim.ogrencibilgisistemi
        PROJECT_PATH: StudentTrackingSystem/StudentTrackingSystem.csproj
        IOS_TFM: net9.0-ios18.0
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet

    scripts:
      - name: Install .NET SDK (9.0)
        script: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir "$DOTNET_PATH" --channel 9.0
          "$DOTNET" --info

      - name: Install MAUI workloads (iOS)
        script: |
          "$DOTNET" workload install ios maui
          "$DOTNET" workload list

      - name: Restore
        script: |
          "$DOTNET" restore "$PROJECT_PATH"

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Debug keys presence
        script: |
          echo "ISSUER len: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "KEY_ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER}"
          echo "P8 len: ${#APP_STORE_CONNECT_PRIVATE_KEY}"
          echo "CERT key len: ${#CERTIFICATE_PRIVATE_KEY}"
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | head -n 1

      - name: Fetch signing files (App Store)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "$CERTIFICATE_PRIVATE_KEY" \
            --create

      - name: Add certificates to keychain + verify
        script: |
          keychain add-certificates
          echo "== Codesigning identities =="
          security find-identity -v -p codesigning || true

          COUNT=$(security find-identity -v -p codesigning | grep -c "Apple" || true)
          if [ "$COUNT" -eq 0 ]; then
            echo "ERROR: No codesigning identities found after importing certificates."
            exit 1
          fi

      - name: Build IPA (Release)
        script: |
          "$DOTNET" publish "$PROJECT_PATH" -c Release -f "$IOS_TFM" /p:BuildIpa=true

      - name: Find IPA
        script: |
          find "$CM_BUILD_DIR" -name "*.ipa" -print

    artifacts:
      - "**/*.ipa"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
